Updates for oxen 11.2
- substantially rewritten create and upgrade script to handle l2
  providers and l2 oxend proxies.
- updated required versions to 11.2 release versions.
- documentation updates for BLS key backup/restore.
- added some info to the README about using oxend as a proxy.

diff --git a/oxen-multi-sn-create b/oxen-multi-sn-create
--- a/oxen-multi-sn-create
+++ b/oxen-multi-sn-create
@@ -2,8 +2,53 @@
 
 set -e
 
-if [ "$#" -ne 1 ] || [[ ! $1 =~ ^[0-9][0-9]$ ]]; then
-    echo "Usage: oxen-multi-sn-create XX where XX is a two-digit number."
+print_help() {
+    cat <<HELP
+Usage: oxen-multi-sn-create NN 'https://l2.provider/url' [backups...]
+Usage: oxen-multi-sn-create NN l2-oxend IP:PORT/PUBKEY [backups...]
+Usage: oxen-multi-sn-create NN
+
+NN is a two-digit number.
+
+Remaining arguments specify Arbitrum One L2 RPC providers:
+
+- if HTTP(S) URLs are provided, they will be listed as l2-provider= lines in
+  the node's config file.  They will be checked to make sure they respond and
+  are returning the correct Arbitrum One chain ID.  (To skip this check, add
+  the argument "nocheck" before the first URL).
+
+- if the providers begin with the argument "l2-oxend" then subsequent
+  parameters are the IP:PORT/PUBKEY values of another oxend to use as a proxy
+  for L2 chain data, or the "ipc:///path/to/oxend.sock" on the current machine.
+  In either case, the target must be set up in l2-proxy mode.  See online
+  documentation for more details.
+
+- if no arguments are provided after the NN at all then this script will look
+  for existing l2-oxend= or l2-provider= lines in existing
+  /etc/oxen/node-NN.conf files and use those values.  This is generally what
+  you want if you are adding new instances to a server with working instances.
+
+Backups can be specified by listing multiple URLs or l2-oxend addresses.
+
+Example using a primary and backup L2-provider:
+
+    oxen-multi-sn-create 00 'https://example.com/arb1rpc' 'https://backup.example.com/arb1'
+
+Example using oxend L2 proxies, where one proxy is node-00 on the same server,
+and the other is a remote node at the given IP/port/pubkey:
+
+    oxen-multi-sn-create 01 l2-oxend \\
+        ipc:///var/lib/oxen/node-00/oxend.sock \\
+        1.2.3.4:9876/d511bcbbf01f739187df45a59501aafaa02cedda678d05cb9aee27f9b91f0caf
+
+(Note that if the proxy is a very old node (installed before Oxen v8), it may
+have different primary pubkey and Ed25519 pubkeys: in such a case you must use
+Ed25519 pubkey rather than the primary SN pubkey here).
+HELP
+}
+
+if [ "$#" -eq 0 ] || [[ ! $1 =~ ^[0-9][0-9]$ ]]; then
+    print_help
     exit 1
 fi
 
@@ -12,7 +57,109 @@ if [ "$UID" -ne 0 ]; then
     exit 1
 fi
 
-PT=$1
+PT="$1"
+shift
+
+l2_setting=
+bad=
+
+if [ "$#" -eq 0 ]; then
+    # No args given: go see if we can find any existing node-NN.conf with
+    # l2-provider= or l2-oxend= in it.  If we find both, we prefer l2-oxend, as
+    # it is probably quite common to have the proxy itself listed with
+    # l2-provider and the others pointing at it via l2-oxend.
+    from=
+    for x in /etc/oxen/node-[0-9][0-9].conf; do
+        if [ -z "$l2_setting" ]; then
+            # Only look for this if we haven't found anything yet:
+            l2prov="$(grep '^l2-provider=.' $x || true)"
+            l2_setting="$l2prov"
+            from="$x"
+        fi
+        # Always look for l2-oxend, because with the 'break' we can only get
+        # here if we either haven't found anything, or have only found
+        # a l2-provider= so far.
+        l2oxend="$(grep '^l2-oxend=.' $x || true)"
+        if [ -n "$l2oxend" ]; then
+            l2_setting="$l2oxend"
+            from="$x"
+            break
+        fi
+    done
+
+    if [ -n "$l2_setting" ]; then
+        echo "Auto-detected the following L2 provider settings from $from:"
+        echo "$l2_setting" | sed -e 's/^/    /'
+        read -p "Press enter to confirm these L2 settings, Ctrl-C to abort."
+    else
+        echo "No l2-oxend= or l2-provider= found in any existing /etc/oxen/node-NN.conf; you need to specify a provider or proxy to use."
+        bad=1
+    fi
+elif [ "$1" = "l2-oxend" ]; then
+    shift
+    if [ "$#" -eq 0 ]; then
+        bad=1
+        echo "No L2 oxend proxies listed after 'l2-oxend', unable to proceed!"
+    fi
+
+    for proxy in "$@"; do
+        if [[ "$proxy" =~ ^([1-9][0-9]*\.){3}[1-9][0-9]*:[1-9][0-9]{0,4}/[a-fA-F0-9]{64}$ ]] || [[ "$proxy" =~ ^ipc://. ]]; then
+            l2_setting="$l2_setting
+l2-oxend=$proxy"
+        else
+            bad=1
+            echo "Invalid l2-oxend proxy address: '$proxy'; expected IP:PORT/PUBKEY"
+        fi
+    done
+else
+    if [ "$1" = "nocheck" ]; then
+        shift
+        if [ "$#" -eq 0 ]; then
+            bad=1
+            echo "No L2 providers listed after 'nocheck', unable to proceed!"
+        fi
+    else
+        for url in "$@"; do
+            outi=$(mktemp)
+            erri=$(mktemp)
+            echo -en "\nChecking '$url'..."
+            if curl -sSX POST "$url" --connect-timeout 10 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' -o "$outi" 2>"$erri"; then
+                if grep '"0xa4b1"' "$outi" >/dev/null; then
+                    echo -e " Success!"
+                else
+                    bad=1
+                    echo -e " Did not find expected Arbitrum One network id \"0xa4b1\" in the L2 provider 'eth_chainId' response:\n-----"
+                    cat "$outi"
+                    echo -e "-----\nThis RPC provider may be on the wrong network\n"
+                fi
+            else
+                bad=1
+                echo -e " Request failed:\n-----"
+                cat "$erri"
+                echo -e "-----\n"
+            fi
+        done
+    fi
+
+    for proxy in "$@"; do
+        l2_setting="$l2_setting
+l2-provider=$proxy"
+    done
+fi
+
+ip=$(curl -sS -4 http://api.ipify.org)
+if [ -z "$ip" ]; then
+    echo "Failed to figure out your public IPv4 address via ipify.org"
+    bad=1
+fi
+
+
+if [ -n "$bad" ]; then
+    echo -e "\n\n\e[31;1mCorrect the errors above and then re-run this script\e[0m\n"
+    exit 2
+fi
+
+
 oxend_conf=/etc/oxen/node-$PT.conf
 ss_conf=/etc/oxen/storage-$PT.conf
 lokinet_conf=/etc/loki/lokinet-router-$PT.ini
@@ -26,30 +173,23 @@ if [ -z "$OVERWRITE" ]; then
     done
 fi
 
-ip=$(curl -sS http://api.ipify.org)
-if [ -z "$ip" ]; then
-    echo "Failed to figure out your public IP via ipify.org"
-    exit 2
-fi
-
 echo "Creating $oxend_conf"
 cat <<EOF >$oxend_conf
 service-node=1
 service-node-public-ip=$ip
-storage-server-port=221$PT
 p2p-bind-port=222$PT
 rpc-admin=127.0.0.1:223$PT
 quorumnet-port=225$PT
 data-dir=/var/lib/oxen/node-$PT
+$l2_setting
 EOF
 mkdir -p /var/lib/oxen/node-$PT
 chown _loki:_loki /var/lib/oxen/node-$PT
 
 echo "Creating $ss_conf"
 cat <<EOF >$ss_conf
-ip=0.0.0.0
-port=221$PT
-lmq-port=202$PT
+https-port=221$PT
+omq-port=202$PT
 oxend-rpc=ipc:///var/lib/oxen/node-$PT/oxend.sock
 data-dir=/var/lib/oxen/storage-$PT
 EOF
diff --git a/oxen-multi-sn-upgrade b/oxen-multi-sn-upgrade
--- a/oxen-multi-sn-upgrade
+++ b/oxen-multi-sn-upgrade
@@ -2,8 +2,49 @@
 
 set -e
 
-if [ "$#" -ne 0 ]; then
-    echo "Usage: oxen-multi-sn-upgrade"
+print_help() {
+    cat <<HELP
+Usage: oxen-multi-sn-upgrade 'https://l2.provider/url' [backups...]
+Usage: oxen-multi-sn-upgrade l2-oxend IP:PORT/PUBKEY [backups...]
+
+Specify one or more l2-providers to add to oxend configs.
+
+To set up all multi-nodes on this machine to communicate directly with an
+Arbitrum One RPC provider, simply run this command with the primary RPC URL
+optionally followed by any backup providers you want to configure that will be
+used if the backup is inaccessible or starts significantly lagging.  For
+example:
+
+    oxen-multi-sn-upgrade 'https://example.com/arb1rpc' 'https://backup.example.com/arb1'
+
+You can also configure oxend in L2 proxy mode to significantly reduce the L2
+provider RPC usage.  This script can configure nodes to use a preconfigured
+oxend proxy, but does not automatically configure the proxy oxend node itself.
+For more details on setting up a proxy, see online Session node documentation.
+
+The listed providers will be tested to make sure they are reachable and are
+providing services for the correct Arbitrum One network; to skip this check add
+the word "nocheck" before the URLs:
+
+    oxen-multi-sn-upgrade nocheck 'http://example.com/xyzrpc' 'https://backup.example.org'
+
+To configure the nodes on this server to use such a proxy run this command with
+one or more address/pubkeys that have been configured to allow this node to use
+the proxy, such as the following (ignore the \\, the command should be entered
+as one single command):
+
+    oxen-multi-sn-upgrade l2-oxend \\
+        10.11.12.13:5678/1ed91b8657b897dcca052343d19df402bf58a90134132266b1634e0bacdf89d2 \\
+        10.20.30.40:9876/d511bcbbf01f739187df45a59501aafaa02cedda678d05cb9aee27f9b91f0caf
+
+(Note that if the proxy is a very old node (installed before Oxen v8), it may
+have different primary pubkey and Ed25519 pubkeys: in such a case you must use
+Ed25519 pubkey rather than the primary SN pubkey here).
+HELP
+}
+
+if [ "$#" -eq 0 ] || [[ "$1" =~ ^- ]]; then
+    print_help
     exit 1
 fi
 
@@ -12,51 +53,75 @@ if [ "$UID" -ne 0 ]; then
     exit 1
 fi
 
+
+l2_setting=
+bad=
+
+if [ "$1" = "l2-oxend" ]; then
+    shift
+
+    for proxy in "$@"; do
+        if [[ "$proxy" =~ ^([1-9][0-9]*\.){3}[1-9][0-9]*:[1-9][0-9]{0,4}/[a-fA-F0-9]{64}$ ]] || [[ "$proxy" =~ ^ipc://. ]]; then
+            l2_setting="$l2_setting\nl2-oxend=$proxy"
+        else
+            bad=1
+            echo "Invalid l2-oxend proxy address: '$proxy'; expected IP:PORT/PUBKEY"
+        fi
+    done
+else
+    if [ "$1" = "nocheck" ]; then
+        shift
+    else
+        for url in "$@"; do
+            outi=$(mktemp)
+            erri=$(mktemp)
+            echo -en "\nChecking '$url'..."
+            if curl -sSX POST "$url" --connect-timeout 10 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' -o "$outi" 2>"$erri"; then
+                if grep '"0xa4b1"' "$outi" >/dev/null; then
+                    echo -e " Success!"
+                else
+                    bad=1
+                    echo -e " Did not find expected Arbitrum One network id \"0xa4b1\" in the L2 provider 'eth_chainId' response:\n-----"
+                    cat "$outi"
+                    echo -e "-----\nThis RPC provider may be on the wrong network\n"
+                fi
+            else
+                bad=1
+                echo -e " Request failed:\n-----"
+                cat "$erri"
+                echo -e "-----\n"
+            fi
+        done
+    fi
+
+    for proxy in "$@"; do
+        l2_setting="$l2_setting\nl2-provider=$proxy"
+    done
+fi
+
+if [ "$#" -eq 0 ]; then
+    echo "No L2 providers given, unable to proceed!"
+    bad=1
+fi
+
+if [ -n "$bad" ]; then
+    echo -e "\n\n\e[31;1mCorrect the errors above and then re-run this script\e[0m\n"
+    exit 1
+fi
+
 oxend_upgrade=()
-ss_upgrade=()
-lokinet_upgrade=()
-ss210_upgrade=()
 
 shopt -s nullglob
 
-echo "Finding lokid->oxend configs that need migration:"
-for x in /etc/loki/node-[0-9][0-9].conf; do
-    ox="${x/loki/oxen}"
-    if [ -e "$ox" ]; then
-        echo "Error: $ox already exists, aborting migration to avoid potentially overwriting things" >&2
-        exit 1
-    fi
-    oxend_upgrade+=("$x")
-    echo "    - $x"
-done
-
-echo "Finding storage server configs that need migration:"
-for x in /etc/loki/storage-[0-9][0-9].conf; do
-    ox="${x/loki/oxen}"
-    if [ -e "$ox" ]; then
-        echo "Error: $ox already exists, aborting migration to avoid potentially overwriting things" >&2
-        exit 1
-    fi
-    ss_upgrade+=("$x")
-    echo "    - $x"
-done
-
-for x in /etc/oxen/storage-[0-9][0-9].conf; do
-    if ! grep -q oxend-rpc= $x; then
-        ss210_upgrade+=("$x")
+echo "Finding oxend configs that need L2 configuration:"
+for x in /etc/oxen/node-[0-9][0-9].conf; do
+    if ! grep -q '^\(l2-oxend\|l2-provider\)' $x; then
+        oxend_upgrade+=("$x")
         echo "    - $x"
     fi
 done
 
-echo "Finding lokinet configs that need upgrading:"
-for x in /etc/loki/lokinet-router-[0-9][0-9].ini; do
-    if grep -q ^jsonrpc $x; then
-        lokinet_upgrade+=("$x")
-        echo "    - $x"
-    fi
-done
-
-if [ "${#oxend_upgrade[@]}${#ss_upgrade[@]}${#lokinet_upgrade[@]}${#ss210_upgrade[@]}" == "0000" ]; then
+if [ "${#oxend_upgrade[@]}" = "0" ]; then
     echo "Nothing to upgrade"
     exit 0
 fi
@@ -65,90 +130,18 @@ restarts=()
 
 if [ "${#oxend_upgrade[@]}" -gt 0 ]; then
     echo -e "\n"
-    read -p "Press enter to move /etc/loki/node-*.conf files to /etc/oxen and switch the active services to oxen-node@XX.service, Ctrl-C to abort."
-    echo
-
-    stops=()
-    starts=()
-    for ox in "${oxend_upgrade[@]}"; do
-        NN=${ox/*node-/}
-        NN=${NN/.conf/}
-        mv -v "${ox}" "${ox/loki/oxen}"
-        if systemctl -q is-enabled loki-node@$NN; then
-            stops+=("loki-node@$NN")
-            starts+=("oxen-node@$NN")
-        fi
-    done
-    if [ "${#stops[@]}" -gt 0 ]; then
-        echo "Switching active services from loki-node@XX to oxen-node@XX"
-        systemctl disable "${stops[@]}"
-        systemctl enable "${starts[@]}"
-        echo "Stopping ${stops[*]}"
-        systemctl stop "${stops[@]}"
-        echo "Starting ${starts[*]}"
-        systemctl start "${starts[@]}"
-    fi
-fi
-
-if [ "${#ss_upgrade[@]}" -gt 0 ]; then
-    echo -e "\n"
-    read -p "Press enter to move /etc/loki/storage-*.conf files to /etc/oxen and switch the active services to oxen-storage-server@XX.service, Ctrl-C to abort."
-    echo
-
-    stops=()
-    starts=()
-    for ox in "${ss_upgrade[@]}"; do
-        NN=${ox/*storage-/}
-        NN=${NN/.conf/}
-        mv -v "${ox}" "${ox/loki/oxen}"
-        if systemctl -q is-enabled loki-storage-server@$NN; then
-            stops+=("loki-storage-server@$NN")
-            starts+=("oxen-storage-server@$NN")
-        fi
-    done
-    if [ "${#stops[@]}" -gt 0 ]; then
-        echo "Switching active services from loki-storage-server@XX to oxen-storage-server@XX"
-        systemctl disable "${stops[@]}"
-        systemctl enable "${starts[@]}"
-        echo "Stopping ${stops[*]}"
-        systemctl stop "${stops[@]}"
-        echo "Starting ${starts[*]}"
-        systemctl start "${starts[@]}"
-    fi
-
-    echo -e "\e[33;1mNOTE: you need to run this script once more to fully migrate storage server!\e[1m"
-fi
-
-if [ "${#lokinet_upgrade[@]}" -gt 0 ]; then
-    echo -e "\n"
-    read -p "Press enter to change the old jsonrpc= option to rpc=... in the above lokinet configs, Ctrl-C to abort."
-
-    for ln in "${lokinet_upgrade[@]}"; do
-        num=${ln/*-/}
-        num=${num/.ini/}
-        perl -pi -e "s{^jsonrpc=.*}{rpc=ipc:///var/lib/oxen/node-$num/oxend.sock}" $ln
-        echo "Updated RPC setting in $ln"
-    done
-
-    restarts+=("lokinet-routers.target")
-fi
-
-if [ "${#ss210_upgrade[@]}" -gt 0 ]; then
-    echo -e "\n"
-    echo -e "About to change the old lokid-rpc-port=PORT option to oxend-rpc=ipc:///var/lib/oxen/node-XX/oxend.sock"
+    echo "About to add the following L2 configuration to the oxend configs listed above:"
+    echo -e "$l2_setting" | sed -e 's/^/    /'
+    echo ""
     read -p "Press enter to continue, Ctrl-C to abort."
 
-    for ss in "${ss210_upgrade[@]}"; do
-        num=${ss/*storage-/}
-        num=${num/.conf/}
-        perl -pi -e "s{lokid-rpc-port=.*}{oxend-rpc=ipc:///var/lib/oxen/node-$num/oxend.sock}" $ss
-        echo "Updated RPC setting in $ss"
+    for ox in "${oxend_upgrade[@]}"; do
+        echo -e "$l2_setting" >>"$ox"
     done
-
-    restarts+=("oxen-storage-servers.target")
+    restarts+=(oxen-nodes.target)
 fi
 
 echo -e "\nAll done."
 if [ "${#restarts[*]}" -gt 0 ]; then
-    echo -e "You probably want to run this now:\n\nsystemctl restart ${restarts[*]}\n"
+    echo -e "\nYou probably want to run this now to restart services with the update configs:\n\n    systemctl restart ${restarts[*]}\n"
 fi
